import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { join } from 'path';
import { dirname } from 'path';
import { fileURLToPath } from 'url';
import db from '../db.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA_DIR = join(__dirname, '..', 'data', 'notebooklm');

/**
 * NotebookLMSync — Upload raw intelligence data to Google Drive for NotebookLM indexing.
 *
 * NotebookLM has no public API. The integration works via Google Drive:
 * 1. Upload Markdown files to a Google Drive folder
 * 2. NotebookLM (linked to that folder) auto-indexes new files
 * 3. Poll or manual trigger for Audio Overview
 *
 * Fallback: If Google Drive API is not available, files are saved locally
 * to local-backend/data/notebooklm/ and logged.
 */
class NotebookLMSync {
  constructor() {
    this.lastSync = null;
    this.syncStatus = 'idle'; // idle | syncing | success | fallback_local | error
    this.googleDriveAvailable = false; // Set true when credentials are configured
    this.ensureLocalDir();
    this.loadConfig();
  }

  loadConfig() {
    // Load folderId and notebookId from DB settings
    try {
      const rows = db.prepare("SELECT * FROM settings WHERE key LIKE 'notebooklm_%'").all();
      for (const r of rows) {
        if (r.key === 'notebooklmFolderId') this.folderId = r.value || '';
        if (r.key === 'notebooklmNotebookId') this.notebookId = r.value || '';
      }
      // Fallback to defaults if DB empty
      if (!this.folderId) this.folderId = '1C1Q5GPypwiPvIHt6acYRHWAKapdr5jof';
      if (!this.notebookId) this.notebookId = 'b27d3277-d416-410e-a48d-dca5a38d5741';
    } catch (e) {
      console.log('[NotebookLMSync] Config load note:', e.message);
      this.folderId = '1C1Q5GPypwiPvIHt6acYRHWAKapdr5jof';
      this.notebookId = 'b27d3277-d416-410e-a48d-dca5a38d5741';
    }
  }

  ensureLocalDir() {
    if (!existsSync(DATA_DIR)) {
      mkdirSync(DATA_DIR, { recursive: true });
    }
  }

  /**
   * Sync megaContext to Google Drive (or local fallback).
   * @param {Object} megaContext — structured intelligence data
   * @param {string} folderName — Google Drive folder name
   * @returns {Object} { success, fileId?, localPath?, filename, source }
   */
  async syncToDrive(megaContext, folderName = 'VNStock_Daily_Intelligence') {
    this.syncStatus = 'syncing';
    this.loadConfig(); // Reload config in case it changed
    try {
      const markdown = await this.createMarkdownFile(megaContext);
      const dateStr = new Date().toISOString().split('T')[0];
      const filename = `vnstock_intelligence_${dateStr}.md`;

      if (this.googleDriveAvailable) {
        const folderId = this.folderId || await this.findOrCreateFolder(folderName);
        const fileId = await this.uploadFile(folderId, filename, markdown);
        this.lastSync = new Date().toISOString();
        this.syncStatus = 'success';
        return {
          success: true,
          fileId,
          folderId,
          filename,
          source: 'google_drive',
          message: `Uploaded to Google Drive folder "${folderName}"`,
        };
      }

      // Fallback: save locally
      const localPath = join(DATA_DIR, filename);
      writeFileSync(localPath, markdown, 'utf-8');
      console.log(`[NotebookLMSync] Fallback: Saved Markdown to ${localPath}`);
      this.lastSync = new Date().toISOString();
      this.syncStatus = 'fallback_local';
      return {
        success: true,
        localPath,
        filename,
        source: 'local_fallback',
        message: `Google Drive API not available. Saved locally to ${localPath}`,
      };
    } catch (error) {
      this.syncStatus = 'error';
      console.error('[NotebookLMSync] Sync error:', error.message);
      return { success: false, error: error.message };
    }
  }

  /**
   * Convert megaContext object to structured Markdown.
   * @param {Object} megaContext
   * @returns {string} Markdown content
   */
  async createMarkdownFile(megaContext) {
    const now = new Date();
    const date = now.toISOString().split('T')[0];
    const time = now.toTimeString().split(' ')[0];

    let md = `# VNStock Daily Intelligence — ${date}\n\n`;
    md += `> Auto-generated by VNStock AI v3.0 | NotebookLM Sync  \n`;
    md += `> Timestamp: ${date} ${time}  \n\n`;
    md += `---\n\n`;

    // Stock Data
    if (megaContext?.stockData) {
      md += `## 📊 Dữ liệu Thị trường (Stock Data)\n\n`;
      const stock = megaContext.stockData;
      if (typeof stock === 'object' && !Array.isArray(stock)) {
        for (const [symbol, data] of Object.entries(stock)) {
          md += `### ${symbol}\n\n`;
          md += `\`\`\`json\n${JSON.stringify(data, null, 2)}\n\`\`\`\n\n`;
        }
      } else {
        md += `\`\`\`json\n${JSON.stringify(stock, null, 2)}\n\`\`\`\n\n`;
      }
    }

    // News
    if (megaContext?.news && Array.isArray(megaContext.news)) {
      md += `## 📰 Tin tức (News)\n\n`;
      for (const item of megaContext.news) {
        md += `### ${item.title || 'Untitled'}\n\n`;
        md += `- **Nguồn:** ${item.source || 'Unknown'}  \n`;
        md += `- **URL:** ${item.url || 'N/A'}  \n`;
        md += `- **Ngày:** ${item.publishedAt || date}  \n\n`;
        md += `${item.summary || item.content || item.description || ''}\n\n`;
        md += `---\n\n`;
      }
    }

    // YouTube Transcripts
    if (megaContext?.youtube && Array.isArray(megaContext.youtube)) {
      md += `## 🎥 YouTube Transcripts\n\n`;
      for (const item of megaContext.youtube) {
        md += `### ${item.title || 'Untitled'} — ${item.channel || 'Unknown Channel'}\n\n`;
        md += `- **URL:** ${item.url || 'N/A'}  \n`;
        md += `- **Duration:** ${item.duration || 'N/A'}  \n`;
        md += `- **Published:** ${item.publishedAt || 'N/A'}  \n\n`;
        md += `${item.transcript || item.summary || ''}\n\n`;
        md += `---\n\n`;
      }
    }

    // Analysis / Insights
    if (megaContext?.analysis) {
      md += `## 🔍 Phân tích Tổng hợp (Analysis)\n\n`;
      md += `${megaContext.analysis}\n\n`;
    }

    if (megaContext?.insights && Array.isArray(megaContext.insights)) {
      md += `### Key Insights\n\n`;
      for (const insight of megaContext.insights) {
        md += `- ${insight}\n`;
      }
      md += `\n`;
    }

    // Watchlist
    if (megaContext?.watchlist && Array.isArray(megaContext.watchlist)) {
      md += `## 👁️ Watchlist\n\n`;
      md += `| Symbol | Action | Rationale |\n`;
      md += `|--------|--------|-----------|\n`;
      for (const item of megaContext.watchlist) {
        md += `| ${item.symbol || '-'} | ${item.action || '-'} | ${item.rationale || '-'} |\n`;
      }
      md += `\n`;
    }

    // Citations
    md += `## 📚 Trích dẫn (Citations)\n\n`;
    md += `1. VNStock AI v3.0 — Báo cáo tự động ngày ${date}.\n`;
    if (megaContext?.sources && Array.isArray(megaContext.sources)) {
      let idx = 2;
      for (const src of megaContext.sources) {
        md += `${idx}. ${src}\n`;
        idx++;
      }
    }
    md += `\n`;

    md += `---\n\n`;
    md += `*Generated by VNStock AI v3.0 — NotebookLM Sync Module*\n`;

    return md;
  }

  /**
   * Find existing folder or create new one on Google Drive.
   * Placeholder — requires Google Drive API credentials.
   */
  async findOrCreateFolder(folderName) {
    if (!this.googleDriveAvailable) {
      console.log(`[NotebookLMSync] Placeholder: Would find/create folder "${folderName}" on Google Drive`);
      return this.folderId || 'placeholder-folder-id';
    }
    // TODO: Implement using googleapis or REST API with service account
    // 1. Search for folder by name
    // 2. If not found, create folder
    // 3. Return folder ID
    throw new Error('Google Drive API not yet implemented. Set googleDriveAvailable=true after configuring credentials.');
  }

  /**
   * Upload file content to Google Drive folder.
   * Placeholder — requires Google Drive API credentials.
   */
  async uploadFile(folderId, filename, content) {
    if (!this.googleDriveAvailable) {
      console.log(`[NotebookLMSync] Placeholder: Would upload "${filename}" (${content.length} bytes) to folder ${folderId}`);
      return 'placeholder-file-id';
    }
    // TODO: Implement using googleapis multipart upload
    // 1. Create file metadata with parents=[folderId]
    // 2. Upload media content
    // 3. Return file ID
    throw new Error('Google Drive API not yet implemented. Set googleDriveAvailable=true after configuring credentials.');
  }

  getStatus() {
    return {
      status: this.syncStatus,
      lastSync: this.lastSync,
      googleDriveAvailable: this.googleDriveAvailable,
      localDir: DATA_DIR,
      folderId: this.folderId || null,
      notebookId: this.notebookId || null,
    };
  }
}

export const notebooklmSync = new NotebookLMSync();
export default NotebookLMSync;
